hosts: [
  { host_ip: "192.168.77.10", host_name: "n1"},
  { host_ip: "192.168.77.11", host_name: "n2"},
  { host_ip: "192.168.77.12", host_name: "n3"},
  { host_ip: "192.168.77.13", host_name: "n4"}
]

obsolete_services:
  - puppet
  - chef-client

centos_files: [
     { src: "centos.sshd_config", dest: "/etc/ssh/sshd_config" }
  ]
