# -*- mode: ruby -*-
# vi: set ft=ruby :
hosts = {
	"n1" => "192.168.77.10",
	"n2" => "192.168.77.11",
	"n3" => "192.168.77.12",
	"n4" => "192.168.77.13"
}
Vagrant.configure("2") do |config|
	if (/cygwin|mswin|mingw|bccwin|wince|emx/ =~ RUBY_PLATFORM) != nil
      config.vm.synced_folder ".", "/vagrant", mount_options: ["dmode=700,fmode=600"]
    else
      config.vm.synced_folder ".", "/vagrant"
    end
	# always use Vagrants insecure key
	config.ssh.insert_key = true
	# forward ssh agent to easily ssh into the different machines
	config.ssh.forward_agent = true
	check_guest_additions = false
	functional_vboxsf = false
	config.vm.box = "bento/ubuntu-16.04"
		hosts.each do |name, ip|
			config.vm.define name do |machine|
			machine.vm.hostname = name
			machine.vm.network :private_network, ip: ip
			machine.vm.provider "virtualbox" do |v|
				v.name = name
			end
		end
	end
	if Vagrant.has_plugin?("vagrant-cachier")
       config.cache.scope = :box
    end
    if Vagrant.has_plugin?("vagrant-vbguest")
       config.vbguest.auto_update = true
       config.vbguest.no_install = false
       config.vbguest.no_remote = false
    end
end